### ISSUE TITLE
API returns 500 http response

### ISSUE THREAD

**Issue by phdelodder** [linuxserver/docker-zoneminder#1]
I'm testing this new container and the API returns a 500 http response. From the logs I found this issue: 

> [Thu Aug 17 05:41:42.516197 2017] [:error] [pid 855] [client 172.17.0.1:59984] PHP Fatal error:  Uncaught Error: Call to undefined function apc_fetch() in /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/Cache/Engine/ApcEngine.php:78
>     \nStack trace:\n#0 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/Cache/Cache.php(363): ApcEngine->read('myapp_cake_core...')\n#1 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/I18n/I18n.php(235): Cache::read('cake_dev_en', '_ca
>     ke_core_')\n#2 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/basics.php(636): I18n::translate('Cache engine "%...', NULL, 'cake_dev')\n#3 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/Cache/Cache.php(184): __d('cake_dev', 'Cac
>     he engine "%...', '_cake_core_')\n#4 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')\n#5 /usr/share/webapps/zoneminder/htdocs/api/app/Config/core.php(375): Cache::config('_cak
>     e_core_', Array)\n#6 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/Core/Configure.php(72): include('/usr/share/weba...')\n#7 /usr/share/webapps/zoneminder/htdocs/api/lib/Cake/bootstrap.php(4 in /usr/share/webapps/zoneminder/htdocs
>     /api/lib/Cake/Cache/Engine/ApcEngine.php on line 78

The reason is because in PHP 7 doesn't have de backwards compatible apcu and apcu there for this needs to be installed: 

apt-get install php-apcu
add to sources 'deb http://ftp.de.debian.org/debian sid main'
apt-get update, apt-get install php-apcu-bc

**Comment by sparklyballs** [comment]
testing locally installing apcu-bc results in a segfault

**Comment by phdelodder** [comment]
I'm trying to create a pull request with the changes to got it working.

**Comment by phdelodder** [comment]
When I do the commands locally, using pecl, it works but when incorporate it in the dockerfile i get a segfault. 


apt-get install php-dev php-pear
apt-get install php-apcu
yes '' | pecl install apcu_bc-beta
echo "extension=apc.so" >> /etc/php/7.0/mods-available/apcu.ini
