### ISSUE TITLE
Run zmupdate.pl to update the database on startup

### ISSUE THREAD

**Issue by michaelarnauts** [linuxserver/docker-zoneminder#17]
The container will not start correctly if zmupdate.pl isn't ran before starting.

I had to run `zmupdate.pl -u root -p` since the default user didn't have enough permissions.

**Comment by thelamer** [comment]
I was not aware this was for database scheme changes, I will test locally and see if we can implement this in the config section of init. 

Linking to current PR:
https://github.com/linuxserver/docker-zoneminder/pull/21

**Comment by thelamer** [comment]
Closing as I will be archiving this repo
