### ISSUE TITLE
wrong timezone

### ISSUE THREAD

**Issue by no-Legend** [linuxserver/docker-zoneminder#20]
I'm not able to connect to the web server.
There is all the time a error message.
ZoneMinder is not installed properly: php's date.timezone does not match the system timezone!

Cheers Robert

**Comment by tobbenb** [comment]
You did see that this isn't released? Not even sure if it's getting released either.

**Comment by no-Legend** [comment]
Should I not report any bugs until it is out of development state.
Nothing will become stable without reporting bugs!

**Comment by j0nnymoe** [comment]
Right now this one isn't ever going to be released. No plans right now to continue development on it.
