### ISSUE TITLE
Apache error log forwarding not working

### ISSUE THREAD

**Issue by senden9** [linuxserver/docker-zoneminder#5]
The Apache error log is not forwarded to the docker log. Following error message from `docker logs -f zoneminder_io`:
```
tail: cannot open '1504187370.5762193240 /var/log/apache2/error.log' for reading: No such file or directory
```
It seems that the timestamp is also forwarded as argument to tail.

**Comment by sparklyballs** [comment]
that's a harmless error caused by reading an internal log to allow s6 to think the app is running in the foreground
