### ISSUE TITLE
Missing ZIP dependency

### ISSUE THREAD

**Issue by senden9** [linuxserver/docker-zoneminder#6]
If I use the provided docker image I can not export a event as ZIP because the `zip` package is not installed. After the installation of `zip` I can create the export archive. Upstream reference: ZoneMinder/ZoneMinder#1974

(Event if I install `zip` I can not download that file but this should be another issue.)

**Comment by sparklyballs** [comment]
php zip or zip itself ?

**Comment by senden9** [comment]
Zip itself. This is also fixed in the upstream. But here is also some other bug because I cant download the archive afterwords. This is not the case in the upstream docker image.

**Comment by sparklyballs** [comment]
i'm gonna add the package to the list direct rather than go through the review process as the image isn't released yet

closing this issue also

**Comment by senden9** [comment]
OK.
Should I open a separate issue for the not working download of the event archive?

**Comment by sparklyballs** [comment]
erm.........

need a bit more info on what is not working and/or what is any error messages etc

**Comment by senden9** [comment]
Sorry for the very short description. Was more a question as a description of the bug. If i have time to recreate this behaviour I will open a new issue and dig me through the logs..

But for now so that you now about what I talk: If I open the export window & click on the export/download button (after selecting what parts of the event should exported) I just come to a white empty window. Normally here would start the download.
