### ISSUE TITLE
Container Separation

### ISSUE THREAD

**Issue by viniciushsantana** [linuxserver/docker-zoneminder#8]
Hi,

I was trying out Zoneminder for a personal project and noticed that most images are using the "everything in the same container" approach. I know there's a lot of scenarios where it does make sense but [usually it is not a good practice](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#each-container-should-have-only-one-concern).

Is there any plans to make individual containers for each service? Or at least an option to use an external database instead of running MySQL internally.

I don't know much about Zoneminder but I think maybe its possible to create individual containers for Apache, PHP, Zoneminder itself and MySQL.

Modularizing the components should make scaling much easier and even give some swapping capabilities in the future, like using Nginx instead of Apache.

Thanks for reading.

**Comment by Pimmetje** [comment]
I think apache and Zoneminder are bound together too much to have separation make sense. Mysql could be separated but as the other are already combined i think that also does not make much sense. At least not for the beginning of this container.

**Comment by tobbenb** [comment]
In our containers we have all that is needed for running the app. Just that it's the intended way to run a container, doesn't mean you have to obey the creators thoughts.
We try to make the container as easy to use as possible and having everything separated into each own container makes it much harder to set up. 

You are free to not use our images and make your own if they don't please your believes on how a container should run.
